openapi: 3.1.0
info:
  title: P10 API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - races
  - grid
paths:
  /races:
    get:
      summary: Get all races for calendar year
      operationId: getRaces
      parameters:
        - name: year
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRacesResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /races/circuits:
    get:
      summary: Get all race circuits for calendar year
      operationId: getRaceCircuits
      parameters:
        - name: year
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRaceCircuitsResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /starting-grid:
    get:
      summary: Get all race circuits for calendar year
      operationId: getStartingGrid
      parameters:
        - name: year
          in: query
          required: false
          schema:
            type: integer
        - name: circuitName
          in: query
          required: true
          schema:
            type: string
        - name: sprint
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStartingGridResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    GetRacesResponse:
      type: object
      required:
        - year
        - races
      properties:
        year:
          type: integer
        races:
          type: array
          items:
            $ref: "#/components/schemas/RaceDetails"

    RaceDetails:
      type: object
      properties:
        roundId:
          type: integer
        circuitName:
          type: string
        isSpringWeekend:
          type: boolean
        sprintDate:
          type: string
          format: date
        raceDate:
          type: string
          format: date
        raceSessionKey:
          type: integer
        sprintSessionKey:
          type: integer

    GetRaceCircuitsResponse:
      type: object
      required:
        - year
        - circuits
      properties:
        year:
          type: integer
        circuits:
          type: array
          items:
            $ref: "#/components/schemas/CircuitRecord"

    GetStartingGridResponse:
      type: object
      properties:
        year:
          type: integer
        grid:
          type: array
          items:
            $ref: "#/components/schemas/GridPositionData"

    CircuitRecord:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    GridPositionData:
      type: object
      properties:
        position:
          type: integer
        driverName:
          type: string
        driverAcronym:
          type: string
        driverTeam:
          type: string
        driverNumber:
          type: integer

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
