openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /races/{year}:
    get:
      summary: Get all races for calendar year
      operationId: getRaces
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRacesResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /races/{year}/circuits:
    get:
      summary: Get all race circuits for calendar year
      operationId: getRaceCircuits
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRaceCircuitsResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    GetRacesResponse:
      type: object
      required:
        - races
      properties:
        races:
          type: array
          items:
            $ref: "#/components/schemas/RaceDetails"

    RaceDetails:
      type: object
      properties:
        roundId:
          type: integer
        circuitName:
          type: string
        isSpringWeekend:
          type: boolean
        sprintDate:
          type: string
          format: date
        raceDate:
          type: string
          format: date
        raceSessionKey:
          type: integer
        sprintSessionKey:
          type: integer

    GetRaceCircuitsResponse:
      type: object
      required:
        - circuits
      properties:
        circuits:
          type: array
          items:
            $ref: "#/components/schemas/CircuitRecord"

    CircuitRecord:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
