openapi: 3.1.0
info:
  title: P10 API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /session-points:
    post:
      summary: List session result for each individual's tip
      operationId: calculateSessionPoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSessionPointsRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSessionPointsResponse'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "./common-schema.yaml#/components/schemas/Error"
components:
  schemas:
    PostSessionPointsRequest:
      type: object
      required:
        - circuitName
        - predictions
      properties:
        year:
          type: integer
        circuitName:
          type: string
        predictions:
          type: array
          items:
            $ref: '#/components/schemas/Prediction'

    PostSessionPointsResponse:
      type: object
      required:
        - year
        - circuitName
        - results
        - firstDnf
      properties:
        year:
          type: integer
        circuitName:
          type: string
        firstDnf:
          type: array
          items:
            type: string
        gpResults:
          type: array
          items:
            $ref: '#/components/schemas/GpPredictionResult'

    Prediction:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        sprintDriver:
          type: string
        raceDriver:
          type: string
        dnfDriver:
          type: string

    GpPredictionResult:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        sprintResult:
          $ref: '#/components/schemas/SessionResult'
        raceResult:
          $ref: '#/components/schemas/SessionResult'
        dnfResult:
          $ref: '#/components/schemas/DnfResult'

    SessionResult:
      type: object
      required:
        - driver
        - position
        - points
      properties:
        driver:
          type: string
        position:
          type: integer
        points:
          type: integer

    DnfResult:
      type: object
      required:
        - driver
        - isFirstDnf
      properties:
        driver:
          type: string
        isFirstDnf:
          type: boolean